version = 1

[[annotations]]
path = ["examples/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Marcin Kaim"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["NOTICE"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Marcin Kaim"
SPDX-License-Identifier = "Apache-2.0"